import React, { useState, useEffect } from 'react';
import { useParams, useLocation } from 'react-router-dom';
import { Api } from '../services/api';
import { EventData } from '../types';

const QuickUpload = () => {
    const { collectionId } = useParams<{ collectionId: string }>();
    const location = useLocation();
    
    // UI State
    const [events, setEvents] = useState<EventData[]>([]);
    const [selectedEventId, setSelectedEventId] = useState("");
    const [files, setFiles] = useState<File[]>([]);
    const [uploading, setUploading] = useState(false);
    const [progress, setProgress] = useState(0);
    const [status, setStatus] = useState("Authenticating...");
    
    // Parse manual event ID from query string (if generated by admin)
    const queryEventId = new URLSearchParams(location.search).get('eventId');
    
    // Manual fallback for extreme cases
    const [manualId, setManualId] = useState("");

    useEffect(() => {
        if(collectionId) {
            loadEvents(collectionId);
        }
    }, [collectionId]);
    
    // Effect to set the event ID if passed in URL
    useEffect(() => {
        if (queryEventId && events.length > 0) {
            // Validate that the event exists in the list (if list loaded successfully)
            const exists = events.find(e => e.event_id === queryEventId);
            if (exists) setSelectedEventId(queryEventId);
        } else if (queryEventId && events.length === 0) {
            // Even if list didn't load (403), we might blindly trust the ID if backend allows
             setSelectedEventId(queryEventId);
        }
    }, [queryEventId, events]);

    const loadEvents = async (id: string) => {
        try {
            const res = await Api.getEvents(id, true); 
            setEvents(res.events || []);
            setStatus("Ready to upload");
        } catch(e) {
            console.error(e);
            // If getEvents fails (403), we can still try to upload IF we have the eventId from URL
            if (queryEventId) {
                 setStatus("Ready to upload (Direct Link Mode)");
                 setEvents([]); // Empty list means we rely on pre-selected ID
            } else {
                 setStatus("Error: Link invalid or expired.");
            }
        }
    };

    const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files) setFiles(Array.from(e.target.files));
    };

    const handleUpload = async () => {
        const cId = collectionId || manualId;
        const eId = selectedEventId || queryEventId;
        
        if (!cId || !eId || files.length === 0) return;
        
        setUploading(true);
        setProgress(0);
        setStatus("Initializing Upload...");
        
        const BATCH_SIZE = 5;
        const totalFiles = files.length;
        let completedCount = 0;
        
        try {
          for (let i = 0; i < totalFiles; i += BATCH_SIZE) {
              const batch = files.slice(i, i + BATCH_SIZE);
              setStatus(`Uploading batch ${Math.floor(i / BATCH_SIZE) + 1} / ${Math.ceil(totalFiles/BATCH_SIZE)}`);
              
              const filePayload = batch.map(f => ({ name: f.name, type: f.type, size: f.size }));
              const { urls } = await Api.generatePublicUploadUrls(cId, eId, filePayload);
              
              await Promise.all(batch.map(async (file, idx) => {
                const urlObj = urls[idx];
                if (urlObj && urlObj.uploadURL) {
                  await fetch(urlObj.uploadURL, {
                    method: 'PUT',
                    body: file,
                    headers: { 'Content-Type': file.type || 'image/jpeg' }
                  });
                }
              }));
              
              completedCount += batch.length;
              setProgress(Math.round((completedCount / totalFiles) * 100));
          }
          setStatus("Upload Complete! You can close this window.");
          setFiles([]);
          alert("All photos uploaded successfully.");
        } catch (e) {
          console.error(e);
          setStatus("Upload Failed. Link might be expired.");
        } finally {
          setUploading(false);
        }
    };

    // If ID is missing entirely
    if(!collectionId) return (
        <div className="min-h-screen bg-black text-white flex flex-col items-center justify-center p-4">
             <div className="bg-gray-900 p-8 rounded-xl text-center">
                 <h2 className="text-xl font-bold text-red-500 mb-4">Invalid Link</h2>
                 <p className="mb-4">Please enter Collection ID manually if you have it:</p>
                 <input className="bg-black border border-gray-700 p-2 rounded text-white mb-4 w-full" placeholder="Collection ID" value={manualId} onChange={e => setManualId(e.target.value)} />
                 <button onClick={() => loadEvents(manualId)} className="bg-brand text-black font-bold px-4 py-2 rounded">Load Events</button>
             </div>
        </div>
    );

    return (
        <div className="min-h-screen bg-[#0a0a0a] text-white flex flex-col items-center justify-center p-4">
            <div className="w-full max-w-lg bg-[#111] border border-gray-800 p-8 rounded-2xl shadow-2xl">
                <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 bg-brand rounded-full flex items-center justify-center text-black font-bold">☁️</div>
                    <div>
                        <h1 className="text-xl font-bold">Quick Upload Portal</h1>
                        <p className="text-xs text-gray-500">Secure Assistant Access</p>
                    </div>
                </div>

                {status.includes("Error") ? (
                    <div className="text-red-500 bg-red-900/20 p-4 rounded border border-red-500/50 mb-4">
                        {status}
                        <button onClick={() => window.location.reload()} className="block mt-2 text-xs underline text-white">Retry</button>
                    </div>
                ) : (
                    <div className="space-y-6">
                        {/* Event Selector: Only show if we didn't get a specific event ID from URL OR if we successfully loaded events list */}
                        {(!queryEventId || events.length > 0) && (
                            <div>
                                <label className="block text-sm text-gray-400 mb-2">Select Event Folder</label>
                                <select 
                                    value={selectedEventId} 
                                    onChange={e => setSelectedEventId(e.target.value)} 
                                    className="w-full bg-black border border-gray-700 p-3 rounded-lg text-white focus:border-brand outline-none"
                                    disabled={!!queryEventId && events.length === 0}
                                >
                                    <option value="">-- Choose Event --</option>
                                    {events.map(e => <option key={e.event_id} value={e.event_id}>{e.name} ({e.event_date})</option>)}
                                </select>
                            </div>
                        )}
                        
                        {/* Direct Link Banner */}
                        {queryEventId && events.length === 0 && (
                            <div className="bg-brand/10 border border-brand/50 p-3 rounded text-sm text-brand">
                                Direct Event Upload Mode Active
                            </div>
                        )}

                        <div className={`border-2 border-dashed rounded-xl p-8 transition flex flex-col items-center justify-center text-center cursor-pointer ${files.length > 0 ? 'border-brand bg-brand/5' : 'border-gray-700 hover:border-gray-500'}`}>
                            <input type="file" multiple accept="image/*" onChange={handleFileSelect} className="hidden" id="q-up" disabled={uploading} />
                            <label htmlFor="q-up" className="cursor-pointer w-full">
                                <div className="text-3xl mb-2">📂</div>
                                <div className="font-bold">Select Photos</div>
                                <div className="text-xs text-gray-500 mt-2">{files.length} files selected</div>
                            </label>
                        </div>

                        {files.length > 0 && !uploading && (
                            <button onClick={handleUpload} className="w-full bg-brand text-black font-bold py-3 rounded-lg hover:brightness-110 shadow-[0_0_15px_rgba(0,230,118,0.3)]">
                                Start Upload
                            </button>
                        )}

                        {uploading && (
                            <div>
                                <div className="flex justify-between text-xs mb-1">
                                    <span className="text-brand font-mono">{status}</span>
                                    <span>{progress}%</span>
                                </div>
                                <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                                    <div className="h-full bg-brand transition-all duration-300" style={{width: `${progress}%`}}></div>
                                </div>
                            </div>
                        )}
                    </div>
                )}
            </div>
            <div className="mt-8 text-xs text-gray-600">EventLens Pro &copy; 2025</div>
        </div>
    );
};

export default QuickUpload;